"""Process-local live-class session storage."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any


logger = logging.getLogger(__name__)

_sessions: dict[str, dict[str, Any]] = {}


def _now() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).isoformat()


def create_session(session_id: str, title: str, subject: str | None = None, depth: str = "medium") -> dict[str, Any]:
    """Create and store an in-memory live-class session.

    Args:
        session_id: Unique identifier generated by the route layer.
        title: Human-readable session title.
        subject: Optional subject hint used during note generation.
        depth: Requested note depth stored with the session.

    Returns:
        The newly created session dictionary.
    """
    session = {
        "session_id": session_id,
        "title": title,
        "subject": subject,
        "depth": depth,
        "status": "started",
        "audio_chunks": [],
        "created_at": _now(),
        "updated_at": _now(),
        "transcript_path": None,
        "note_path": None,
    }
    _sessions[session_id] = session
    logger.info(
        "Created live-class session session_id=%s depth=%s subject_provided=%s",
        session_id,
        depth,
        subject is not None,
    )
    return session


def get_session(session_id: str) -> dict[str, Any] | None:
    """Return an in-memory session by ID, or None when it is absent."""
    return _sessions.get(session_id)


def add_chunk_to_session(session_id: str, file_path: str) -> int:
    """Record an uploaded audio chunk path against a live-class session.

    Args:
        session_id: Existing live-class session identifier.
        file_path: Local path to the stored audio chunk.

    Returns:
        The number of chunks currently associated with the session.

    Raises:
        KeyError: If the session does not exist.
    """
    session = get_session(session_id)
    if not session:
        logger.warning("Cannot add audio chunk because session is missing session_id=%s", session_id)
        raise KeyError(f"Session not found: {session_id}")
    session.setdefault("audio_chunks", []).append(file_path)
    session["updated_at"] = _now()
    logger.info(
        "Recorded audio chunk for live-class session session_id=%s chunk_count=%s",
        session_id,
        len(session["audio_chunks"]),
    )
    return len(session["audio_chunks"])


def update_session(session_id: str, **fields: Any) -> dict[str, Any] | None:
    """Update stored session metadata and refresh its update timestamp.

    Args:
        session_id: Existing live-class session identifier.
        **fields: Metadata fields to merge into the session dictionary.

    Returns:
        The updated session dictionary, or None when the session is absent.
    """
    session = get_session(session_id)
    if not session:
        logger.warning("Cannot update missing live-class session session_id=%s", session_id)
        return None
    session.update(fields)
    session["updated_at"] = _now()
    logger.info(
        "Updated live-class session session_id=%s status=%s fields=%s",
        session_id,
        fields.get("status"),
        sorted(fields.keys()),
    )
    return session
