"""Durable, file-backed live-class session storage.

Sessions used to live in a process-local dict, which meant a session created
by one worker process was invisible to another (or lost on restart). This
module stores the same data in a SQLite file under STORAGE_DIR instead, so
session state survives process restarts and is shared by every worker process
running against the same STORAGE_DIR.

SQLite (not Redis/Postgres) was chosen deliberately: it needs no new service
dependency, it already fits this service's existing local-disk storage model
(see file_storage.py), and WAL mode gives safe concurrent access from multiple
worker processes on one host. It does not span multiple hosts unless
STORAGE_DIR is a shared network volume -- the same constraint the existing
audio/transcript/note storage already has.
"""

from __future__ import annotations

import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.config import settings

logger = logging.getLogger(__name__)

_COLUMNS = (
    "session_id", "title", "subject", "depth", "status",
    "created_at", "updated_at", "transcript_path", "note_path", "error",
)


def _db_path() -> Path:
    """Return the SQLite file path for session storage, creating its directory."""
    root = Path(settings.STORAGE_DIR)
    root.mkdir(parents=True, exist_ok=True)
    return root / "sessions.db"


def _connect() -> sqlite3.Connection:
    """Open a SQLite connection with WAL mode for multi-process safety."""
    conn = sqlite3.connect(_db_path(), timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.row_factory = sqlite3.Row
    return conn


def _ensure_schema(conn: sqlite3.Connection) -> None:
    """Create the sessions table if it does not already exist."""
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS sessions (
            session_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            subject TEXT,
            depth TEXT NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            transcript_path TEXT,
            note_path TEXT,
            error TEXT
        )
        """
    )


def _now() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).isoformat()


def _row_to_session(row: sqlite3.Row) -> dict[str, Any]:
    """Convert a SQLite row into the session dictionary shape callers expect."""
    return {column: row[column] for column in _COLUMNS}


def create_session(session_id: str, title: str, subject: str | None = None, depth: str = "medium") -> dict[str, Any]:
    """Create and persist a live-class session.

    Args:
        session_id: Unique identifier generated by the route layer.
        title: Human-readable session title.
        subject: Optional subject hint used during note generation.
        depth: Requested note depth stored with the session.

    Returns:
        The newly created session dictionary.
    """
    now = _now()
    session = {
        "session_id": session_id,
        "title": title,
        "subject": subject,
        "depth": depth,
        "status": "started",
        "created_at": now,
        "updated_at": now,
        "transcript_path": None,
        "note_path": None,
        "error": None,
    }
    with _connect() as conn:
        _ensure_schema(conn)
        conn.execute(
            """
            INSERT INTO sessions
                (session_id, title, subject, depth, status, created_at, updated_at, transcript_path, note_path, error)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                session["session_id"], session["title"], session["subject"], session["depth"], session["status"],
                session["created_at"], session["updated_at"], session["transcript_path"], session["note_path"], session["error"],
            ),
        )
    logger.info(
        "Created live-class session session_id=%s depth=%s subject_provided=%s",
        session_id,
        depth,
        subject is not None,
    )
    return session


def get_session(session_id: str) -> dict[str, Any] | None:
    """Return a persisted session by ID, or None when it is absent."""
    with _connect() as conn:
        _ensure_schema(conn)
        row = conn.execute(
            "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
        ).fetchone()
    return _row_to_session(row) if row else None


def update_session(session_id: str, **fields: Any) -> dict[str, Any] | None:
    """Update persisted session metadata and refresh its update timestamp.

    Args:
        session_id: Existing live-class session identifier.
        **fields: Metadata fields to merge into the session record. Only
            recognized session columns are written.

    Returns:
        The updated session dictionary, or None when the session is absent.
    """
    writable_fields = {key: value for key, value in fields.items() if key in _COLUMNS and key != "session_id"}
    with _connect() as conn:
        _ensure_schema(conn)
        existing = conn.execute(
            "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
        ).fetchone()
        if not existing:
            logger.warning("Cannot update missing live-class session session_id=%s", session_id)
            return None

        writable_fields["updated_at"] = _now()
        assignments = ", ".join(f"{column} = ?" for column in writable_fields)
        conn.execute(
            f"UPDATE sessions SET {assignments} WHERE session_id = ?",
            (*writable_fields.values(), session_id),
        )
        row = conn.execute(
            "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
        ).fetchone()

    logger.info(
        "Updated live-class session session_id=%s status=%s fields=%s",
        session_id,
        fields.get("status"),
        sorted(writable_fields.keys()),
    )
    return _row_to_session(row)
